### ISSUE TITLE
docs: link to available search field needs updating

### ISSUE THREAD

**Issue by richardgmcmahon** [andycasey/ads#106]
In Examples section of docs; the link to available search fields does not work and gives a 404 error:

see: https://ads.readthedocs.io/en/latest/#examples

A list of available search fields is here: https://github.com/adsabs/adsabs-dev-api/blob/master/search.md#fields

I think it could be changed to

https://adsabs.github.io/help/search/comprehensive-solr-term-list

Also, there some useful examples of your API usage at:

https://github.com/adsabs/ads-examples

**Comment by smoh** [comment]
Hi Andy, Could you update the docs? You fixed this issue already in b5333966ba25a951bd81a1624d1938fff574ea8c already but the docs pages have not been updated. According to [readthedocs](https://readthedocs.org/projects/ads/builds/), the latest build was 2 years ago.

**Comment by jonnybazookatone** [comment]
@andycasey

**Comment by andycasey** [comment]
(Better late than never 😅 )

The complete list of available search fields is documented for version 1 of the ``ads`` package: https://ads.readthedocs.io/en/v1/getting-started/document.html#fields-and-operators

I won't update the existing documentation because it will soon be superseded.
