### ISSUE TITLE
author_count return None

### ISSUE THREAD

**Issue by richardgmcmahon** [andycasey/ads#107]
I tried to get the author_count back  but the value None is being returned.

e.g.
``
import ads

papers = list(ads.SearchQuery(q="supernova", sort="citation_count",
                          fl=['author', 'title', 'first_author',
                              'citation_count', 'author_count']))

print(papers[0].title)
print(papers[0].first_author)
print(papers[0].citation_count)
print(papers[0].author_count)

``

returns:

[u'Observational Evidence from Supernovae for an Accelerating Universe and a Cosmological Constant']
Riess, Adam G.
11226
None

**Comment by jonnybazookatone** [comment]
Looks like Solr doesn't return a value for a lot of those articles. Is this field supported @aaccomazzi?

**Comment by aaccomazzi** [comment]
It's searchable but not stored in solr, so no, at the moment it can't be retrieved.  Would consider adding it if there were interesting use cases, otherwise just do a `len(authors)`

**Comment by jonnybazookatone** [comment]
Thanks!
