### ISSUE TITLE
citation_count returns None

### ISSUE THREAD

**Issue by zingale** [andycasey/ads#110]
It seems that some new papers have a `citation_count` of `None` instead of `0`.  This is problematic when sorting by `citation_count` since `None` cannot be cast to an integer.

## Expected Behavior

`None` should not be a valid value here.  The library should automatically change a `None` to `0`.

## Steps to Reproduce (for bugs)

I am not sure how reproducible this is, as I suspect it is for new papers.  But I am hitting the issue with bibcode `2019arXiv191012979H`.  If I can still reproduce tomorrow, then I'll add detailed steps.  Otherwise, I suspect we are just catching ADS in a temporary state, which the library should work around.

## Your Environment

Running with python 3.7.4, ads 0.12.3 (installed via pip)

**Comment by jonnybazookatone** [comment]
I'm indifferent about the approach for giving back a zero vs. a `None`. As it stands, all we know is the search engine doesn't return a value, not that the paper has zero citations. We'd be happy to look at a PR for a general solution if you have one in mind.

If you just want to get things working, you can either pre-sort the results using the `sort` keyword in `ads.SearchQuery`:

```
In [1]: q = ads.SearchQuery(q='star', fl=['title', 'citation_count'], sort='citation_count')

In [2]: papers = [i for i in q]

In [3]: [k.citation_count for k in papers]
Out[3]:
[11783,
 10022,
 9309,
 9004,
 6778,
 6482,
....
]
```

alternatively, if you're sorting some curated list further down a script, you can use `sorted` to handle `None`s in some way like:
```
In [1]: q = ads.SearchQuery(q='star', fl=['title', 'citation_count'])

In [2]: papers = [i for i in q]

In [3]: papers[3].citation_count = None

In [4]: [k.citation_count for k in sorted(papers, key=lambda x: (x.citation_count is not None, x.citation_count), reverse=True)]
Out[4]:
[421,
 134,
 134,
 73,
 71,
 60,
 57,
 53,
 51,
 44,
 44,
....,
None
]
```

**Comment by andycasey** [comment]
In these situations, I think this package should probably change a `None` to 0. This might have been fixed automatically in (unstable) version `v1` of this code. The following code:

```python
from ads import Document

docs = (
    Document.select()
            .order_by(Document.entry_date.desc())
            .limit(10)
)

for doc in docs:
    print(f"{doc} added {doc.entry_date} has {doc.citation_count} citations")
```

Gives this output:
```
<Document: bibcode=2022arXiv220111122C> added 2022-01-27 02:30:43 has 0 citations
<Document: bibcode=2022arXiv220111123S> added 2022-01-27 02:30:43 has 0 citations
<Document: bibcode=2022arXiv220111121D> added 2022-01-27 02:30:43 has 0 citations
<Document: bibcode=2022arXiv220111120O> added 2022-01-27 02:30:43 has 0 citations
<Document: bibcode=2022arXiv220111044L> added 2022-01-27 02:30:42 has 0 citations
<Document: bibcode=2022arXiv220111049B> added 2022-01-27 02:30:42 has 0 citations
<Document: bibcode=2022arXiv220111090B> added 2022-01-27 02:30:42 has 0 citations
<Document: bibcode=2022arXiv220111092C> added 2022-01-27 02:30:42 has 0 citations
<Document: bibcode=2022arXiv220111064S> added 2022-01-27 02:30:42 has 0 citations
<Document: bibcode=2022arXiv220111059T> added 2022-01-27 02:30:42 has 0 citations
```

I'll close this issue now, but if anyone finds an example where this is still happening (in either version of the code), please re-open it and give the bibcode.
