### ISSUE TITLE
support for Positional Field Searches

### ISSUE THREAD

**Issue by richardgmcmahon** [andycasey/ads#120]
I would like to run some positional searches to identify papers with the author is second or third as described here

https://ui.adsabs.harvard.edu/help/search/positional

e.g.

pos(author:”Oort, J”,2) | papers which have “J. Oort” as the second author

I tried q='pos(author:”Oort, J”,2)' 

papers = list(ads.SearchQuery(q=q,
                         fl=['id', 'first_author',
                             'title', 'year', 'citation_count],
                         sort='citation_count desc'))
                         
This returns:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rgm/anaconda3/lib/python3.7/site-packages/ads/search.py", line 501, in __next__
    self.execute()
  File "/Users/rgm/anaconda3/lib/python3.7/site-packages/ads/search.py", line 533, in execute
    self.session.get(self.HTTP_ENDPOINT, params=self.query)
  File "/Users/rgm/anaconda3/lib/python3.7/site-packages/ads/base.py", line 94, in load_http_response
    raise APIResponseError(http_response.text)

**Comment by andycasey** [comment]
Sorry for the >1 year reply @richardgmcmahon! It seems I missed a few GitHub notifications for this repository...

There _should_ always have been support in the client for positional field searches because I've used them myself for some years. They seem to work for me with this code snippet (adapted from yours):

```python
import ads

q = 'pos(author:"Oort, J", 2)'
papers = list(ads.SearchQuery(q=q, fl=['id', 'first_author', 'title', 'year', 'citation_count'], sort='citation_count desc'))

for paper in papers:
    print(f"{paper.id} {paper.first_author} {paper.title[0]}")
```

Shows:
```
1253773 van der Kruit, P. C. The Radio Emission of NGC 4258 and the Possible Origin of Spiral Structure
1142525 Rougoor, G. W. Distribution and Motion of Interstellar Hydrogen in the Galactic System with Particular Reference to the Region Within 3 Kiloparsecs of the Center
...
```

Can you try it and re-open this if it is still an issue?
