### ISSUE TITLE
Not able to use timeAllowed and cursorMark combination

### ISSUE THREAD

**Issue by Ajaya1997** [andycasey/ads#122]
we are trying to fetch the details from solr with REST API call but we are getting error like:
{
  "responseHeader":{
    "zkConnected":true,
    "status":400,
    "QTime":2,
    "params":{
      "q":"node:0",
      "fl":"",
      "cursorMark":"*",
      "sort":"id asc",
      "timeAllowed":"10",
      "rows":"10",
      "wt":"json",
      "facet":"off"}},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException",
      "error-class","org.apache.solr.client.solrj.impl.BaseHttpSolrClient$RemoteSolrException",
      "root-error-class","org.apache.solr.client.solrj.impl.BaseHttpSolrClient$RemoteSolrException"],
    "msg":"Error from server at null: Can not search using both cursorMark and timeAllowed",
    "code":400}}

Query I'm using :
**{HOST}:{PORT}/solr/{COLLECTION_NAME}/select?q=node:0&sort=id%20asc&wt=json&cursorMark=*&rows=100&fl=&facet=off&timeAllowed=1000**

tried removing the timeAllowed param as well but still getting the error response:
**{HOST}:{PORT}/solr/{COLLECTION_NAME}/select?q=node:0&sort=id%20asc&wt=json&cursorMark=*&rows=100&fl=&facet=off**

please give suggestion it's bit urgent. Solr version we are using 8.4.1.

**Comment by andycasey** [comment]
This is a Solr restriction on the server end (not the client end) which disables using use both cursorMark and timeAllowed in the one query. I'm sorry, but there's nothing I can do to help with that because it's a server-side choice.
