### ISSUE TITLE
404 not found, API change

### ISSUE THREAD

**Issue by JohannesBuchner** [andycasey/ads#128]
Queries now all give: `ads.exceptions.APIResponseError: '{"message":"Not found"}\n'`

Looking at the docs ([example](https://ui.adsabs.harvard.edu/help/api/api-docs.html#get-/search/query)), the endpoint is 
`/search/query`, not `/search/query/`.

Removing the slash at the end in config.py solves this.

**Comment by andycasey** [comment]
Merged #129. Bumped new minor version (0.12.7). Released new minor version on GitHub, and uploaded it to PyPI. Thanks for finding and fixing this.
