### ISSUE TITLE
trunk: set sane default `fl`

### ISSUE THREAD

**Issue by vsudilov** [andycasey/ads#22]
`fl` should have sane defaults (bibcode, author, first_author,...), as the adsws-api returns only an internal integer id for the record if `fl` is not specified

**Comment by andycasey** [comment]
I am currently working on this on https://github.com/andycasey/ads/tree/devel-article-attributes

For fields that are not returned, if the `id` is available, it can be accessed via a background query. Or do you think that if the object wasn't instantiated with a particular field, it should never be accessible?

**Comment by vsudilov** [comment]
I think the client should come with sane defaults, but not try to interpret/act on behalf of a user beyond that. Therefore I'd say if the user wants to pass `fl=None` to his query, then they should get what they ask for.

**Comment by vsudilov** [comment]
@romanchyla suggests using both: default `fl`, and lazy loading fields that don't make it. That does require someone to maintain and synchronize field names with the search engine schema, which may or may not be a deal breaker.

**Comment by andycasey** [comment]
It's not a deal-breaker for me, and I think it is convenient to use lazy loading for the typical non-heavy user that just wants to do a few things.

I have arbitrarily specified `id`, `author`, `year`, and `bibcode` as the default `fl` fields, which are enough to print `__repr__` and to check equality between two `Articles`.

**Comment by vsudilov** [comment]
:+1: (and btw the stubdata is a great place to look for interesting fields)

**Comment by vsudilov** [comment]
Also closed in e858529d0c5ad5125fa5eb27c4593dd66161f3a2
