### ISSUE TITLE
TypeError: 'module' object is not callable in top-cited-astronomers.py

### ISSUE THREAD

**Issue by manodeep** [andycasey/ads#31]
I just forked the project and I am getting this error: 

--------------------
$ python top-cited-astronomers.py

Traceback (most recent call last):
  File "top-cited-astronomers.py", line 10, in <module>
    most_cited_papers = ads.search(sort="citations", filter="database:astronomy", rows=200)
TypeError: 'module' object is not callable
--------------------

**Comment by vsudilov** [comment]
Hi,

That script hasn't been updated since the api compatibility update a few months ago. On the bright side, updating it is straightforward ;)

**Comment by manodeep** [comment]
Is there a documented way of making said straightforward change ? :)

**Comment by vsudilov** [comment]
The API is (hopefully) documented sufficiently well in the README.md to update those example scripts. No worries if you'd rather not make this changes -- I didn't mean to imply expectation on my part.

**Comment by manodeep** [comment]
No worries. I was hoping to use this module for a dotastro hackday. Hopefully I can create a new script by following along the example on the homepage. 

Thanks !

**Comment by JohannesBuchner** [comment]
It does not seem trivial to change: Changing the line 

`most_cited_papers = ads.search(sort="citations", filter="database:astronomy", rows=200)`

to

`most_cited_papers = list(ads.SearchQuery(sort="citations", rows=200))`

does not work since q must not be empty.

**Comment by vsudilov** [comment]
Hi,

specifying `q="*"` should do the trick.

**Comment by jonnybazookatone** [comment]
This *should* be fixed in #51. Please re-open if there are further issues.

**Comment by manodeep** [comment]
Works for me. Thanks for the fix
