### ISSUE TITLE
How to get a pandas DataFrame with results?

### ISSUE THREAD

**Issue by cdeil** [andycasey/ads#35]
I'd like to do some analysis with a list of articles obtained with:
```
articles = list(ads.SearchQuery(author='something'))
```
- histogram of articles per year
- most-cited articles
- scatter plot of number of authors versus publication date

For this it would be really helpful to have `articles` as a pandas DataFrame.
I'm trying to get this now, but it's a bit painful with missing values as None, ...

If someone here has working examples or even a utility function to put (part of?) the info in the list of articles into a pandas.DataFrame), it would be great if you could share it.

**Comment by jonnybazookatone** [comment]
Have you found something to suit your needs yet? Your question is quite broad, that I don't think there's one solution to them all. But you could access the `json` attribute of the `Article` object:
```python
>>> import ads.sandbox as ads
>>> import pandas as pd
>>>
>>> q = ads.SearchQuery(q='star')
>>> q.execute()
>>> df = pd.DataFrame.from_dict(q.response.json['response']['docs'])
>>> print(df)
                                                title  year  
0   [Cyclic Adenosine 3',5'-Monophosphate during G...  1971  
1   [GRB120404A: GROND observations show steeply d...  2012  
2                [GROND observations of GRB 120311A.]  2012  
3                  [GRB 120324A: GROND observations.]  2012
...
...
>>> df['year'] = pd.to_numeric(df['year'], errors='ignore')
>>> df['year'].plot.hist()
```

![example](https://cloud.githubusercontent.com/assets/633540/15490674/2e7c42cc-2138-11e6-8fdb-dff5e3d17327.jpg)

**Comment by jonnybazookatone** [comment]
I'll close this given the broad scope, but feel free to re-open it if you have strong feelings.
