### ISSUE TITLE
ADS_DEV_KEY environment variable and ads.config.token

### ISSUE THREAD

**Issue by Morisset** [andycasey/ads#37]
Hi,

Thanks a lot for your code, it save hours (days) of work for me and my colleagues!
It seems that once the ADS_DEV_KEY environment variable is defined, any manual change using ads.config.token is not taken into account. It would perhaps be easier when dealing with various token to have the possibility to change it from ads.config.token, rather than updating the environment variable.
Best regards,
Christophe

**Comment by vsudilov** [comment]
Hi Christophe,

Thanks for catching this unintuitive behavior!

Could you explain a bit more your workflow regarding setting/updating tokens? setting `ads.config.token` was meant as a one-time initialization step in the same way as setting environmental variables or writing to those config files. One can always make the query object and set the token on that directly after instantiation:

    query = ads.SearchQuery(q='q')
    q.token = 'token'

but maybe there's a better way for your use case that we can support.

**Comment by Morisset** [comment]
Hi Vladimir,
For unknown reasons, in the print_results in my program (https://github.com/Morisset/SNI_ads), when I use some methods of papers objects (still don't know which one), it calls ADS. It should not, as all the values have been downloaded in previous stage and this method is only a printing one. I also realized that the program is working very well without any connection (this goes in the direction that everything was known before entering this method), so when entering the method I store the token in some variable and then do 
ads.config.token = ''
The rest of the program runs and at the end I reset the token to the original value. But I realized that when I have the ADS_DEV_KEY environment variable defined, it does not take into account the trick and connect to ADS, burning some of the 5000 tickets/day I have. It may be an is one print a lot of time. 

I was thinking that the token from ads.config was a variable (or even a property) and that changing its value would change the behavior.

**Comment by vsudilov** [comment]
For the reasons stated above and that it seems your issue's root cause was issue #38, I won't be refactoring `ads.config.token`. I've added a optional `token` kwarg to the `SearchQuery` constructor that will set the token at init. I think that should be fine for workflows that require changing tokens frequently.
