### ISSUE TITLE
Article.volume don't save None value and have to reconnect to ADS

### ISSUE THREAD

**Issue by Morisset** [andycasey/ads#38]
Hi,

I found some very strange behavior. The following code illustrate the problem:
https://github.com/Morisset/SNI_ads/blob/master/test_get_volume.py
I think the problem comes from werkzeug.utils.cached_property which does not receive a correct value the first time the call to ADS is done. It should store None in the __dict__, but it stores nothing. Then it has to reconnect to ADS to obtain the correct value (not sure this is clear...).
Ch.

**Comment by vsudilov** [comment]
This is due from the fact that the ADS api doesn't return non-existent fields for records, regardless of the `fl`. The solution is to use explicitly set all fields in `fl` to `None` independently of the ADS api response.

Thanks for the catch.

**Comment by Morisset** [comment]
Thanks for your answer. I don't see how practically I can change the code to avoid the secondary calls to ADS when volume is None...

**Comment by vsudilov** [comment]
I'd probably use a defaultdict based on response.params['fl'] here:

`https://github.com/andycasey/ads/blob/master/ads/search.py#L265`

I assigned myself and I'll take care of it, but if you want to make a PR that's fine too -- just please include tests if you do.

**Comment by Morisset** [comment]
I think it's better if you follow the case, I'm leaving tonight for some holidays ;-)
