### ISSUE TITLE
access the Physics abstracts

### ISSUE THREAD

**Issue by Morisset** [andycasey/ads#42]
Hi,

Is there any way to ask the SearchQuery to be done including the Physics abstracts, like in the web form?
Thanks,
Christophe

**Comment by jonnybazookatone** [comment]
`SearchQuery` is not picking a specific database by default. The search engine by default is accessing all of the ADS databases (*astronomy*, *physics*, and *general*). If you want to specify which database you want to specifically access, you can use the *database* field name, for example,

```python
q = SearchQuery(q='author:"^Morisset, C." database:physics')
```

You can play around with the same syntax on the new ADS interface (https://ui.adsabs.harvard.edu) if you copy/paste `author:"^Morisset, C." database:physics` into the search box. For the options you can specifiy via the client (api) take a look here: https://github.com/adsabs/adsabs-dev-api/blob/master/search.md
