### ISSUE TITLE
Default fields used in SolrQuery

### ISSUE THREAD

**Issue by jonnybazookatone** [andycasey/ads#43]
Currently, the default fields used in a SolrQuery are the following:

```
DEFAULT_FIELDS = ["author", "first_author", "bibcode", "id", "year",
                      "title", "reference", "citation"]
```

We've had several users that have run into rate limit problems, as they're requesting information that wasn't retrieved in the initial search, and are lazy loaded, for example "volume". Some ways to fix this are:
  1. Force them to fill in the 'fl’ keyword
  2. Extend the defafult fields
  3. Update the help pages, and emphasise the use of ‘fl’

Option 1 means new users can simply go, and start using the article object straight away, but requires some thought.

Option 2 isn't as appealing, as such operations as 'citation' can be lengthy in terms of time, and can lead to time outs if your connection is terrible. This is a major annoyance if you simply need the bibcode.

Option 3 is the least invasive, but means they have to read the docs....

If you have no preference, we're happy to open a PR to address this.

**Comment by vsudilov** [comment]
Hi,

Since you are dealing with the fallout of users hitting ratelimits, I think it makes sense if you decide which option to use. I'm happy to implement the solution you choose, or review a PR.
