### ISSUE TITLE
Retrieve article through url?

### ISSUE THREAD

**Issue by Gabriel-p** [andycasey/ads#56]
I usually need to grab articles from my Zotero database and get their bibtex from ADS.

Is this package able to fetch the bibtex if I pass the ads url to the article?

**Comment by jonnybazookatone** [comment]
I assume your Zotero entry has an identifier for your article to give the URL (i.e., a bibcode). 

For example:
`https://ui.adsabs.harvard.edu/#abs/2016LPI....47.2774E/abstract`
or
`http://adsabs.harvard.edu/abs/2016LPI....47.2774E`
The documents identifier (bibcode) in this case is `2016LPI....47.2774E`

If so, you can use this client to get the bibtex:

```python
>>> import ads
>>> e = ads.ExportQuery(bibcodes=['2016LPI....47.2774E'], format='bibtex')
>>> print e.execute()

@INPROCEEDINGS{2016LPI....47.2774E,
   author = {{Elliott}, J. and {Huang}, Y.-H. and {Minton}, D.~A. and {Freed}, A.~M.
        },
    title = "{The Length of Lunar Crater Rays Explained Using Secondary Crater Scaling}",
booktitle = {Lunar and Planetary Science Conference},
     year = 2016,
   series = {Lunar and Planetary Science Conference},
   volume = 47,
    month = mar,
    pages = {2774},
   adsurl = {http://adsabs.harvard.edu/abs/2016LPI....47.2774E},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

The README has several examples.

**Comment by Gabriel-p** [comment]
Thanks @jonnybazookatone. I'm thinking on adding an intermediate function to resolve full urls that come from ads, arXiv, doi, stacks.iop.org, and some main journals.

It would be ideal (for my workflow) to just paste whatever url I have at hand and expect the ADS bibtex.
