### ISSUE TITLE
Bibtex method no longer works  (no attribute bibcode)

### ISSUE THREAD

**Issue by ryanvarley** [andycasey/ads#57]
Example

```
papers = list(ads.SearchQuery(aff="*stromlo*"))
first_paper = papers[0]
first_paper.bibtex
```
Gives `AttributeError: 'Article' object has no attribute 'bibcode'`

**Comment by irbdavid** [comment]
I have the same issue I think.  I can verify my API token works using curl, but can't get any results from any queries - either attribute errors or empty values are returned for every example I try:

```
In [35]: q = ads.SearchQuery(q='star', fl=['id', 'bibcode', 'title', 'citation_count'])
In [36]: for paper in q: print(paper.title, paper.citation_count)
None None
...
```

Python 3.5.1 / Anaconda 2.4.0 (x86_64) / IPython 4.0.0

**Comment by ryanvarley** [comment]
The bibtex code still works, i think `bibcode` is just no longer being assigned to the class.
https://github.com/andycasey/ads/blob/master/ads/search.py#L237

i.e this does work
```
from .export import ExportQuery
ExportQuery(bibcodes="2008Natur.452..329S", format="bibtex").execute()
```

**Comment by jonnybazookatone** [comment]
This was a problem introduced on the ADS API side the other day, and should be fixed now (https://github.com/adsabs/solr-service/pull/13). Thanks for raising the issue.
