### ISSUE TITLE
Exception handling in Unicode representation of Articles

### ISSUE THREAD

**Issue by takerukoushirou** [andycasey/ads#59]
In the article method `__unicode__()`, the article properties `first_author`, `bibcode` and `year` are used. This can yield an exception if the fields are not included in the original search query; generally for `first_author` as no getter exists, or if deferred loading for `bibcode` and `year` fails.

Cf. pull request #55 for a more detailed discussion of the issue.

**Comment by vsudilov** [comment]
I think using lazy-loaders in `__unicode__()` isn't correct: `print()` should be a read-only operation.

We can still show meaningful output on `print()` by accessing the instance attribute `_raw` and setting some meaningful defaults:

```
def __unicode__(self):
        author = self._raw.get("first_author", "Unknown author")
        if len(self._raw.get("author", []) > 1:
            author += " et al."
        return u"<{author} {year}, {bibcode}>".format(
            author=author,
            year=self._raw.get("year", "Unknown year"),
            bibcode=self._raw.get("bibcode", "Unknown bibcode"),
        )
```

Thoughts?

**Comment by jonnybazookatone** [comment]
Yeah. I think this is a nicer way to go for this and #59. Also less of a headache if there's changes in the future.

**Comment by takerukoushirou** [comment]
Definitively better to make it read-only and it'll put the `_raw` property to good use 😄 

Another thought on this: If we would always include fields that are being used internally (so far `bibcode`, `first_author` and `year`) in search requests, they should always carry correct information, i.e. the text representation of an article may not state "Unknown author" even though the user included `first_author_norm` in the search query and that field is not empty (which may be confusing for the user). Currently AFAIK only `id` is always included in the `fl` parameter. This would also improve the equality operator as `bibcode` would always be a valid value for articles retrieved via queries.

**Comment by vsudilov** [comment]
Cool, I'll throw up a PR to address these two issues in the near future.

Agree with @takerukoushirou about adding these fields to `fl`. Seeing "unknown" or whichever message should be not happen as a result of normal, "default" usage.

@jonnybazookatone one of `first_author_norm`/`first_author` should be deprecated, right?

**Comment by takerukoushirou** [comment]
Regarding the first author, in my opinion those are different fields and none should be seen as deprecated (unless of course it's deprecated in ADS). The normalised `first_author_norm` only features an abbreviated name with initials, whereas the normal `first_author` shows the full name (if available). The abbreviated name can be quite painful in some situations as names easily overlap, especially if the last name is rather generic...

**Comment by jonnybazookatone** [comment]
`first_author_norm` and `author_norm` should be truncated and ASCII versions of `first_author` and `author`. So they will most likely be deprecated, unless we find a reason not to. So, I'd stick to using `first_author` and `author`.

**Comment by takerukoushirou** [comment]
@jonnybazookatone in that case we should probably also re-add the getter for `first_author` for consistency (initially part of PR #55, but had been removed as suggested during the discussions).

All fields that will be fetched per default in search queries would normally no longer require a getter, as they should be present during normal use (all queried fields are set to `None` if not present in the result set).
Articles can be created manually though, as done in the test cases. Are there actually real usage scenarios involving those? If so, an article could be manually created and receive a known ID. In that case we may consider leaving the getters intact for those articles to still be able to lazily fetch field values.
