### ISSUE TITLE
Article equality operator inconsistencies and bibcode getter

### ISSUE THREAD

**Issue by takerukoushirou** [andycasey/ads#60]
In pull request #55, the following issue appeared:

> The test fails for Python 3 only because of Python 2 and 3 differences in the `hasattr()` function used in the equality operator for articles. Since `bibcode` is now a deferred property, it will raise an `APIResponseError` as it cannot dynamically fetch the `bibcode` property of the LHS article in `test_equals()`, as that article is empty and hence has no ID set. This exception is, in contrast to Python 2, not caught by Python 3's `hasattr()` and propagates. The test expects a `TypeError` raised by the equality operator though.
> 
> I think the equality operator for articles should be fixed to behave identical for both Python 2 and 3.

Currently the test issue is resolved by explicitly setting `bibcode` to `None`, but the behaviour of the equality operator still differs between Python versions. PR #55 contains a suggested fix by @jonnybazookatone.

**Comment by vsudilov** [comment]
Same solution as #59? (Make `__eq__()` an operation without side-effects by accessing what we want to compare from `_raw` directly)
