### ISSUE TITLE
Getting associated articles

### ISSUE THREAD

**Issue by astrofrog** [andycasey/ads#67]
I'm trying to access the 'Associated articles' section for e.g.:

http://adsabs.harvard.edu/abs/2013AJ....146...62M

In this case, I should be able to find the erratum. Is there a recommended way to do this?

**Comment by jonnybazookatone** [comment]
So, this currently isn't accessible via the API, in the sense that the search engine does not currently store the association of articles for such things as erratum. There's a ticket somewhere on the ADS side that is open for this to be incorporated. I'll put it here when someone gives me the link.

**Comment by jonnybazookatone** [comment]
The relevant issue for this being available via the API is here: https://github.com/adsabs/ADSimportpipeline/issues/89.

Given there's no API functionality currently, I'm going to close this ticket -- re-open if you think otherwise.
