### ISSUE TITLE
Bibtex issue

### ISSUE THREAD

**Issue by sidereomundi** [andycasey/ads#73]
## Expected Behavior
Hello,

I would like to extract the url of the ADS page associated to each entry. I got it from the bibtex entry, but bibtex does always return none when query from the field. More specifically, querying with the following:
papers = list(ads.SearchQuery(author=myname, max_pages=6,fl=['citation_count', 'bibcode', 'title', 'bibtex','year','author']))

does always provide a None for papers[0].bibtex (as well as other entries)

Am I making some error?

Thanks!

Alex

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (hint: `python -c "import ads; print(ads.__version__)"`)
* Python version (hint: `python -V`)

**Comment by vsudilov** [comment]
Hi,

Could you fill out the steps to reproduce please (I guess I just need "myname" specifically) ? Is it still a bug for other author names?

**Comment by sidereomundi** [comment]
Hi

Yes,

e.g. also the following:

In [1]: import ads.sandbox as ads

In [2]: myname = "Rossi, A"

In [3]: papers = list(ads.SearchQuery(author=myname, max_pages=6, database
= "*",fl=['citation_count', 'bibcode', 'title', 'bibtex','year','author']))

In [4]: print papers[0].author
[u'Sudilovsky, Oscar', u'Pestana, Angel', u'Hinderaker, Paul H.', u'Pitot,
Henry C.']

In [5]: print papers[0].year
1971

In [6]: print papers[0].bibtex
None



While instead:
In [1]: import ads.sandbox as ads

In [2]: myname = "Rossi, A"

In [3]: papers = list(ads.SearchQuery(author=myname, max_pages=6, database
= "*"))

In [4]: print papers[0].author
[u'Sudilovsky, Oscar', u'Pestana, Angel', u'Hinderaker, Paul H.', u'Pitot,
Henry C.']

In [5]: print papers[0].year
1971

In [6]: print papers[0].bibtex
/home/saro/Python/yes/lib/python2.7/site-packages/ads/utils.py:23:
UserWarning: You are lazy loading attributes via 'bibtex', and so are
making multiple calls to the API. This will impact your overall rate limits.
  UserWarning,
@ARTICLE{2013A&A...552A.143S,
   author = {{Sudilovsky}, V. and {Greiner}, J. and {Rau}, A. and
{Salvato}, M. and
    {Savaglio}, S. and {Vergani}, S.~D. and {Schady}, P. and {Elliott}, J.
and
    {Kr{\"u}hler}, T. and {Kann}, D.~A. and {Klose}, S. and {Rossi}, A. and
    {Filgas}, R. and {Schmidl}, S.},
    title = "{Clustering of galaxies around gamma-ray burst sight-lines}",
  journal = {\aap},
archivePrefix = "arXiv",
   eprint = {1302.6362},
 keywords = {gamma-ray burst: general, galaxies: statistics},
     year = 2013,
    month = apr,
   volume = 552,
      eid = {A143},
    pages = {A143},
      doi = {10.1051/0004-6361/201321247},
   adsurl = {http://adsabs.harvard.edu/abs/2013A%26A...552A.143S},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

Thanks a lot!

Alex

**Comment by sidereomundi** [comment]
Hi

Yes,

e.g. also the following:

In [1]: import ads.sandbox as ads

In [2]: myname = "Rossi, A"

In [3]: papers = list(ads.SearchQuery(author=myname, max_pages=6, database = "*",fl=['citation_count', 'bibcode', 'title', 'bibtex','year','author']))

In [4]: print papers[0].author
[u'Sudilovsky, Oscar', u'Pestana, Angel', u'Hinderaker, Paul H.', u'Pitot, Henry C.']

In [5]: print papers[0].year
1971

In [6]: print papers[0].bibtex
None



While instead:
In [1]: import ads.sandbox as ads

In [2]: myname = "Rossi, A"

In [3]: papers = list(ads.SearchQuery(author=myname, max_pages=6, database = "*"))

In [4]: print papers[0].author
[u'Sudilovsky, Oscar', u'Pestana, Angel', u'Hinderaker, Paul H.', u'Pitot, Henry C.']

In [5]: print papers[0].year
1971

In [6]: print papers[0].bibtex
/home/saro/Python/yes/lib/python2.7/site-packages/ads/utils.py:23: UserWarning: You are lazy loading attributes via 'bibtex', and so are making multiple calls to the API. This will impact your overall rate limits.
  UserWarning,
@ARTICLE{2013A&A...552A.143S,
   author = {{Sudilovsky}, V. and {Greiner}, J. and {Rau}, A. and {Salvato}, M. and
    {Savaglio}, S. and {Vergani}, S.~D. and {Schady}, P. and {Elliott}, J. and
    {Kr{\"u}hler}, T. and {Kann}, D.~A. and {Klose}, S. and {Rossi}, A. and
    {Filgas}, R. and {Schmidl}, S.},
    title = "{Clustering of galaxies around gamma-ray burst sight-lines}",
  journal = {\aap},
archivePrefix = "arXiv",
   eprint = {1302.6362},
 keywords = {gamma-ray burst: general, galaxies: statistics},
     year = 2013,
    month = apr,
   volume = 552,
      eid = {A143},
    pages = {A143},
      doi = {10.1051/0004-6361/201321247},
   adsurl = {http://adsabs.harvard.edu/abs/2013A%26A...552A.143S},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

Thanks a lot!

Alex

**Comment by vsudilov** [comment]
The issue comes from including `bibtex` in the `fl`. `bibtex` isn't a field that is returned by ADS search directly; it is computed dynamically.

For now just remove it from the `fl`. We'll address this by removing `@cached_property` from `bibtex` and `metrics`. (N.B. there is no way to make those queries via `ads.Article` without making an additional API call)

**Comment by sidereomundi** [comment]
Thanks!

Alex
