### ISSUE TITLE
limit-request-line parameter

### ISSUE THREAD

**Issue by fbeutler** [andycasey/ads#75]
Hi
I am running the following query to get citations of a large list of papers

    # list_of_ids looks like this ['arXiv:astro-ph/0206283', 'arXiv:1511.04236']
    ads_results = ads.SearchQuery(q=' OR '.join(list_of_ids), fl=['citation_count', 'identifier'])
    ads_results.max_pages = 100
    for ads_item in ads_results:
        print ads_item.identifier, ads_item.citation_count

This all works, but if I make the list of papers very large, like 200 papers or so I am getting the following error

Traceback (most recent call last):
...
    raise APIResponseError(HTTPResponse.text)
ads.exceptions.APIResponseError: u'<html>\n  <head>\n    <title>Bad Request</title>\n  </head>\n  <body>\n    <h1><p>Bad Request</p></h1>\n    Request Line is too large (4607 &gt; 4094)\n  </body>\n</html>\n'

which google tells me is caused by the --limit-request-line flag for request. Is there a way to change this flag in this package?
thanks

**Comment by vsudilov** [comment]
Hi,

URLs can only be so long, and you're constructing a very long url in the form of `/search/?q=id1 OR id2 OR id3 ...`.

In general that's not the right approach for this type of query. If you can get the bibcodes, you could try https://github.com/adsabs/adsabs-dev-api/blob/master/search.md#post-a-large-query, though this client doesn't yet support that endpoint.

Given what's supported today, I'd suggest batching your query into multiple smaller amounts. Keep in mind that each query will count towards your ADS daily api limits.

**Comment by fbeutler** [comment]
well the ads daily limit is the reason I want to put them together... and the --limit-request-line flag does allow to set an unlimited url length...

**Comment by vsudilov** [comment]
that's an nginx param that we don't have control over, and it breaks the HTTP RFC anyways.
