### ISSUE TITLE
[meta] tag pip releases

### ISSUE THREAD

**Issue by vsudilov** [andycasey/ads#78]
`andycasey/ads` should start tagging releases corresponding to pip versions. This allows for more straightforward bug reports and investigations, see e.g. #76, #77.

This issue does not necessarily relate to how often pip is updated unless @andycasey want's to comment on that.
## Expected Behavior

As a maintainer, I want to know which version of the code a bug/feature report stems from.
## Current Behavior

We currently have no git tags, so correlating pip release with commit is extremely difficult.
## Possible Solution

Every pip release should result in a `git tag`. Update the `issues.md` template file to ask for `ads.__version__`, which should also be updated on every pip release.

**Comment by vsudilov** [comment]
FWIW I think git-flow targeting a `develop` branch would just be unnecessary overhead -- mainly because work has historically occured in small, synchronous bursts.

Happy to be convinced otherwise, don't feel too strongly one way or another.

**Comment by guillochon** [comment]
What is the rationale for deciding when `andycasey/ads` currently gets pip releases? In particular, the minor releases seem like they should be pushed out fairly regularly, especially if there are known issues in prior releases.

**Comment by vsudilov** [comment]
We don't have one yet, it's whenever Andy has time and/or inclination :)

**Comment by andycasey** [comment]
Yeah, I tried to update pip each time there was a hotfix, but we should definitely have a defined rationale. I'm "offline" on a day off today, but I will get this set up tomorrow.

**Comment by vsudilov** [comment]
Maybe git flow does make sense -- a release becomes bump version string, promote from develop->master, and let travis-ci package+upload to pypi

Want me to look into how to get travis to do that for us?

**Comment by andycasey** [comment]
I've been failing at most things in life lately,...

I've set up Travis so that it should automatically deploy tagged commits on master as a new version to PyPI. 

So I think now we would just have to make sure that any commits with an updated version strings also get tagged. Is that right?

**Comment by vsudilov** [comment]
I'd suggest any new `git tag` points to a commit that contains only modifications to the version string -- That is, keep version bump commits distinct from feature/bugfix/refactor commits.

Looks like we're good to go; thanks.
