### ISSUE TITLE
Big Queries supported?

### ISSUE THREAD

**Issue by aaronlauterer** [andycasey/ads#84]
Are big queries supported?
The examples are kind of blank regarding this.
I found some BIGQUERY_URL in the config.py but that's about it.

**Comment by jonnybazookatone** [comment]
This client doesn't currently have any API interface to the `bigquery` end point. However, you can look at the ADS help pages on how to interact with the `bigquery` end point directly using the `requests` package.

The fastest option is to open an issue on the ADS help pages, or send them an e-mail at `adshelp@cfa.harvard.edu` to ask them the best way to do this. 

If you prefer to try it anyway, you can do the following that should work:

They used to have a policy of not encouraging the use of `bigquery`, so the examples on https://github.com/adsabs/adsabs-dev-api/blob/47b1b2dd561c2930df3aec7a5df1f12408499826/search.md won't work, as the `biquery` end point is limited to internal use at the moment (iirc; https://github.com/adsabs/solr-service/blob/master/solr/views.py#L149).

Instead, it was encouraged to use the `myads`/`vault` end point:
  1. create a query, and store it in their `store-query` end point
  2. execute the bigquery via `execute-query` end point
  3. retrieve the results and conform it to an `ads.Article` object

You can see an implementation of that here: https://github.com/adsabs/tugboat/blob/master/tugboat/views.py#L73

If you implement it then open a PR, it would be much appreciated by many :).

**Comment by jonnybazookatone** [comment]
I should note, the second step uses a `queryid` to carry out the search on the Solr engine. This doesn't always have the same behaviour as normal searches.

**Comment by aaronlauterer** [comment]
Okay, thanks! I'll look into it and see what I can contribute.

**Comment by jonnybazookatone** [comment]
Cool, I'll close this ticket then.
