### ISSUE TITLE
README on PyPI not very readable

### ISSUE THREAD

**Issue by cdeil** [andycasey/ads#86]
The PyPI page for ADS currently shows raw Markdown from the README: https://pypi.python.org/pypi/ads/0.12.2

See http://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work

Would you be OK with a README change in format to RST?
(pandoc can do it mostly automatic)

Or implement #12 and move most of the README content to docs?

**Comment by andycasey** [comment]
Either would be very much appreciated! Working on #12 is best for the long-term, but it entirely depends on the time that you (and any other potential contributors) have available!

**Comment by cdeil** [comment]
I can do it today, it's not much work.

Do you agree to leave the README mostly empty?
Some people want to have docs in the README in addition, and what I find is that it's hard to maintain and extend the documentation in two places.

This is what I do for most other projects I work on: https://github.com/astropy/regions

OK?

**Comment by andycasey** [comment]
OK for me -- as long as there is a direct link on how to get started! (I
can make a PR to your fork for any minor things like that)
