### ISSUE TITLE
How to store Article objects locally?

### ISSUE THREAD

**Issue by cdeil** [andycasey/ads#88]
I'm working on a gamma-ray data collection where we have data for a few 100 papers:
https://github.com/gammapy/gamma-cat

Now we'd like to build a custom webpage and Python client to browse and analyse that data.

As one part of information we'd like to have basic information (bibcode, title, date, authors, maybe abstract) for these few 100 papers locally available and not make queries to ADS.

My idea was that I use this Python package to do the queries and then for each Article store `__dict__` in a JSON or YAML file to have it available locally and accessible from the webpage.
Is that the best way, or would it be useful enough to have a `to_dict` and maybe even `from_dict` method on `Article` that does the serialisation and possible clever things?

Is that legal or a violation of ADS to extract that much information and store it locally / distribute it via a Github repo / second web page (http://gamma-sky.net/)?

**Comment by vsudilov** [comment]
The `SearchQuery` and `Article` objects should serialize nicely with pickle. `ApiResponse`, used within `SearchQuery` has the raw JSON response in it. With those two things I personally don't see big value in implementing load/dump specifically, but I'm open to the idea and would be happy to review a PR.

AFAIK what you're trying to do should be totally fine, but neither I nor this software represent the ADS. If you're concerned, ping them directly via their support channels.
