### ISSUE TITLE
Get Bibtex

### ISSUE THREAD

**Issue by Gabriel-p** [andycasey/ads#9]
When working with LaTeX you'll need the Bibtex snippet that NASA/ADS provides. Is there a command to obtain it already built in? If not, could it be added?

**Comment by andycasey** [comment]
You can lazy-load BiBTeX through:

````python
import ads
papers = list(ads.SearchQuery(q="star"))
print(papers[0].bibtex)
````

Or many with `ExportQuery` by providing bibcodes:
````python
q = ads.ExportQuery([paper.bibcode for paper in papers[:5]])
print(q.execute())
````
