### ISSUE TITLE
SearchQuery choking on certain ArXiv queries

### ISSUE THREAD

**Issue by guillochon** [andycasey/ads#91]
## Expected Behavior
A valid bibcode passed to `SearchQuery` should return an `Article` object.

## Current Behavior
Certain publications, in particular those with ArXiv bibcodes, seem to return nothing.

## Steps to Reproduce (for bugs)
```Python
import os
import ads

path = 'ads.key'
if os.path.isfile(path):
        with open(path, 'r') as f:
                    ads.config.token = f.read().splitlines()[0]

q = list(ads.SearchQuery(bibcode='2014ApJ...793...38A'))
print(q)
```
returns an article object, as expected, but change the query to the following bibcode:
```Python
q = list(ads.SearchQuery(bibcode='2016arXiv160902927L'))
```
and an empty list is returned.

## Context
This prevents a large number of ADS queries from successfully completing (15 out of 72 that I tested).

## Your Environment
Python version 3.5

**Comment by guillochon** [comment]
OK, figured this out: The bibcodes I was using are the "old" bibcodes, before they are reassigned to a permanent bibcode after publication. I have to use the `alternate_bibcode` field instead. Not sure if this behavior makes sense to me, on the ADS page you can use *either* bibcode without issue.

**Comment by jonnybazookatone** [comment]
Yes, this is a *feature* of the ADS system itself, and not the client. The field **bibcode** will contain the "latest" bibcode assigned to that document, but they retain all previous bibcodes in the field **alternate_bibcode** if they are changed. This happens to all articles that go from an "arXiv" bibcode, to that of a "publisher" bibcode.

You can also use the **identifier** field if you want, which *should* contain all of the identifiers for that document. Although, you should confirm this with the ADS themselves. For example:

```python
>>> q = ads.SearchQuery(identifier='2016arXiv160902927L')
>>> p = list(q)[0]
>>> p.bibcode
 '2016NatAs...1E...2L'
>>> p.alternate_bibcode
 ['2016arXiv160902927L']
>>> p.identifier
 ['2016arXiv160902927L',
 '2016NatAs...1E...2L',
 '2016arXiv160902927L',
 '10.1038/s41550-016-0002',
 '1609.02927']
 '10.1038/s41550-016-0002']
```
