### ISSUE TITLE
Including libraries in the API

### ISSUE THREAD

**Issue by jonnybazookatone** [andycasey/ads#93]
## Expected Behavior

I've been thinking about including libraries in the API, or at least deciding how it should function.

## Possible Solution

Possible behaviour could be:

```python
>>> lq = LibraryQuery()
>>> libraries = lq.execute()
>>> print(libraries)
[Library<'Library', 'Description', 'Public', 'id: f8dsuf8dsf'>),
Library<....>,
Library<....>,]
```
The library would have a library object, for which it would have accessible attributes:
```python
>>> lib = libraries[0]
>>> lib.name
'Library'
```

The attached bibcodes would be Article objects:
```python
>>> lib.bibcodes
[Article<"Author et al., 2012">,
Article<"Author et al. 2014">
```

You could also request specific libraries if you know their id:
```python
>>> lq = LibraryQuery(id='59fier9fre')
>>> my_library = lq.execute()
Library<'Lib', 'id:59fier9fre'>
```

If I have time, I'd also include add/removal of bibcodes in the first release:

```python
>>> lib.remove(['2012MNRAS'])
200, success
>>> lib.add([Article<"Author et al. 2014">])
200, success
```

## Context

Include an API to ADS libraries that would have the following abilities:
  * Collect all of a users libraries with bibcodes
  * Query specific libraries via their id
  * Allow add/remove

What the first release would not include:
  * modification of public/private
  * permission handling
  * description/title modification
  * fancy handling of errors from failed add/remove

**Comment by jonnybazookatone** [comment]
Should also add -- is there any need to include this in the API, over say, BigQuery?

**Comment by vsudilov** [comment]
What is the signature of `LibraryQuery()`? I guess you could pass it a "query" that corresponds to a specific user? I'd like to question if it makes sense copy the `SearchQuery` interface for this feature.

Did you have any specific input you needed?

**Comment by jonnybazookatone** [comment]
At the moment there's no search functionality for libraries on the ADS side. Token -> user's libraries. You can request/access someone else's library if it's public (and you know the ID).

LibrarQuery was just to keep a similar format to the other query classes, but doesn't have to be that way.

Input: would anyone even use this, it's a relatively large addition, which is only worth it if it's useful. I can think of other things like BigQuery that is most likely less work and less complex.

**Comment by vsudilov** [comment]
Not sure how to gauge interest in libraries-- I'd say go for it if you're keen on adding it personally.

I have noticed the big query use case come up many times though.

**Comment by minzastro** [comment]
I would like to use libraries API. More precisely, I need an option to add papers to the library.
Cannot make it running directly via API somehow - I get 
`{'error': 'You passed the wrong type. See the API documentation: http://adsabs.github.io/help/api/'}`
when I try to post something like
`https://api.adsabs.harvard.edu/v1/biblib/documents/...id...?action=add&bibcode=2016yCat..35970030A`

**Comment by jonnybazookatone** [comment]
Thanks for showing interest. This type of question is more appropriate for the ADS github pages, as this library doesn't support ADS libraries (https://github.com/adsabs).

However, here's a quick answer. As the error message states, there's something wrong with your usage of the API. You can see how to use the API at the dev-api pages: https://github.com/adsabs/adsabs-dev-api/blob/master/libraries.md. What you're trying to do should look something like this (didn't check, but should work after some tweaking):

```python
import requests

library_id = 'library ID'
ads_token = 'my token'

r = requests.post(
    'https://api.adsabs.harvard.edu/v1/biblib/documents/{}'.format(library_id),
    data={
        'bibcode': ['2016yCat..35970030A'],
        'action': 'add'
    },
    headers={'Authorization: Bearer {}'.format(ads_token)}
)
```

You can find more details at this set of un-merged documentation: https://github.com/adsabs/adsabs.github.io/blob/new-api/content/v1/libraries.md. Or you can look at how the tests used the API: https://github.com/adsabs/biblib-service/blob/master/biblib/tests/
