### ISSUE TITLE
Feature Request: search by arxiv-id

### ISSUE THREAD

**Issue by lzkelley** [andycasey/ads#97]
There are situations in which I have an arxiv ID, and I would like to get the ADS entry (for example) to retrieve the bibcode for the paper.  Currently, I can query arxiv (using something like https://github.com/lukasschwab/arxiv.py), find the DOI from there, then query ads using the doi to finally get the entry and bibcode.

It would be awesome if there was a way to directly query by arxiv id, like the html api (i.e. http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:XXXX.XXXXX).

**Comment by vsudilov** [comment]
Hi,

Does making a fielded query against `identifier` and/or `alternate_bibcode` (as documented in https://github.com/adsabs/adsabs-dev-api/blob/master/search.md#fields) work for this use case?

**Comment by lzkelley** [comment]
`alternate_bibcode` does not work with an arxiv ID, but `identifier` does!  Sorry I missed this in the docs.  Thanks for pointing it out.

**Comment by jonnybazookatone** [comment]
Just to clarify:
* `identifer`: will contain all identifiers ever used (in theory) arXiv, ADS arXiv bibcode, ADS bibcode, etc.
* `alternate_bibcode`: will contain the ADS bibcode that was constructed (but modified) from the original arXiv identifier, e.g., `2014arXiv1409.7699E` rather than `arXiv:1409.7699`
 
You can also use the field map `arxiv` like:
```python
ads.SearchQuery(q='arxiv:1409.7699')
```
but in the end the search engine is just mapping `arxiv` to `identifier` under the hood....

**Comment by lzkelley** [comment]
Interesting.  I did try just using `q='1409.7699'`, which didn't seem to work; it needs the `arxiv:` specification?

**Comment by jonnybazookatone** [comment]
Yes, you need the `arxiv` field. But like I said, all that happens is the parser turns `arxiv` into `identifier`. So `arxiv:1409.7699` = `identifier:1409.7699`, I guess it's only useful for readability in your script....

When you do an 'unfielded' search, i.e., `q='1409.7699'`, the query parser has a default rule for what it is searching for. Currently, it does a search combined on author, title, and abstract, with weighting:
* `author^1.5 title^1.4 abstract^1.3 all`

You can see this here: https://github.com/romanchyla/montysolr/blob/2d2f8e315f427e6ebd3276ffbfb3ffa6ac1a6b3a/contrib/examples/adsabs/server/solr/collection1/solrconfig.xml#L625

**Comment by jonnybazookatone** [comment]
And forgot to directly answer your second part. `identifier` is a stored field, and so you're doing a fielded search when you specify `arxiv`.

You can see a list of the stored and virtual fields here: https://adsabs.github.io/help/search/comprehensive-solr-term-list

**Comment by lzkelley** [comment]
Very helpful, thanks for the explanations @jonnybazookatone!
