### ISSUE TITLE
Non-lazy loading leads to missing properties in SeachQuery

### ISSUE THREAD

**Issue by lzkelley** [andycasey/ads#98]
A lazy query is giving me normal, valid responses with all of the properties in place and seemingly valid.  Adding `fl` parameters however breaks some of those parameters (example below) giving "Unknown author" and "Unknown year" responses.

## Steps to Reproduce (for bugs)

```
bib = '2010ApJ...725L..91K'
papers = ads.SearchQuery(bibcode=bib)
for pp in papers:
    print(pp, pp.bibcode)

papers = ads.SearchQuery(bibcode=bib, fl=['bibcode'])
for pp in papers:
    print(pp, pp.bibcode)

```
Produces the output:
```
<Kelley, Luke Zoltan et al. 2010, 2010ApJ...725L..91K> 2010ApJ...725L..91K
<Unknown author Unknown year, 2010ApJ...725L..91K> 2010ApJ...725L..91K
```

## Your Environment
```
print(ads.__version__)
print(sys.version)
> 0.12.3
> 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
  [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
```

**Comment by vsudilov** [comment]
Hi,

Nice catch. This is a side effect of the choice to not use lazy loading in the `Article` classes' `__unicode__`/`__str__` method.

I agree that the current behavior is unintuitive and I don't see a reason to not change it.

**Comment by lzkelley** [comment]
Ah, I see, interesting.  Yeah, I just checked and accessing those same elements directly (i.e. `pp.article`) still works fine.  It's easy to use that as a fix for me, but yeah... seems like there's no reason not to (low-priority) fix the `__unicode__` usage too.  Thanks!
